
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: auth
        run: echo ${{ secrets.NOT_SSH }} >> ~/.ssh/known_hosts
        
      - name: deploy
        run: |
          echo deploying to shaneraible.com
          ssh ${{ secrets.USER }}@${{ secrets.SERVER }}
          ls
